name: nonchev
channels:
  - defaults
  - https://conda.anaconda.org/conda-forge
  - main
  - r
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.9.1
  - atk-1.0=2.38.0
  - aws-c-auth=0.7.25
  - aws-c-cal=0.7.3
  - aws-c-common=0.9.27
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.7
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - awscli=2.17.31
  - awscrt=0.21.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - cffi=1.16.0
  - cfitsio=4.4.1
  - colorama=0.4.6
  - cryptography=40.0.2
  - dav1d=1.2.1
  - distro=1.8.0
  - expat=2.6.3
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - ghostscript=10.03.1
  - giflib=5.2.2
  - graphite2=1.3.13
  - graphviz=12.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - icu=75.1
  - imagemagick=7.1.1_38
  - jbig=2.1
  - jmespath=1.0.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libaec=1.1.3
  - libarchive=3.7.4
  - libavif16=1.1.1
  - libcurl=8.9.1
  - libde265=1.0.15
  - libdeflate=1.21
  - libdicom=1.0.5
  - libedit=3.1.20191231
  - libev=4.33
  - libexif=0.6.21
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgd=2.3.3
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libheif=1.18.2
  - libhwy=1.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libmatio=1.5.27
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libpng=1.6.43
  - librsvg=2.58.3
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libvips=8.15.3
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - ncurses=6.4
  - nspr=4.35
  - nss=3.98
  - openjpeg=2.5.2
  - openslide=4.0.0
  - openssl=3.3.2
  - pango=1.54.0
  - pcre2=10.44
  - perl=5.32.1
  - pip=24.0
  - pixman=0.43.2
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - poppler=24.04.0
  - poppler-data=0.4.12
  - prompt_toolkit=3.0.38
  - pthread-stubs=0.4
  - pyopenssl=23.1.1
  - pysocks=1.7.1
  - python=3.9.18
  - python_abi=3.9
  - pyvips=2.2.3
  - rav1e=0.6.6
  - readline=8.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - s2n=1.5.0
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.2
  - svt-av1=2.2.1
  - termcolor=2.4.0
  - tk=8.6.13
  - urllib3=1.26.19
  - wcwidth=0.2.13
  - wheel=0.43.0
  - x265=3.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.1
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - anndata==0.10.8
      - annoy==1.17.3
      - ansicolors==1.1.8
      - anyio==4.4.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.8
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==24.1.0
      - autopep8==2.3.1
      - babel==2.15.0
      - bbknn==1.6.0
      - beartype==0.18.5
      - beautifulsoup4==4.12.3
      - biopython==1.84
      - bleach==6.1.0
      - botocore==1.31.17
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - chex==0.1.86
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - colored==2.2.4
      - comm==0.2.2
      - configargparse==1.7
      - connection-pool==0.0.3
      - contextlib2==21.6.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==3.0.11
      - dask==2024.7.1
      - dask-expr==1.1.9
      - dask-image==2024.5.3
      - datasets==2.20.0
      - datashader==0.16.3
      - datrie==0.8.2
      - debugpy==1.8.3
      - decorator==5.1.1
      - decoupler==1.7.0
      - defusedxml==0.7.1
      - dill==0.3.8
      - diot==0.2.3
      - distributed==2024.7.1
      - docrep==0.3.2
      - docutils==0.21.2
      - dpath==2.2.0
      - einops==0.8.0
      - entrypoints==0.4
      - etils==1.5.2
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fastcluster==1.2.6
      - fasteners==0.19
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - flax==0.8.5
      - fonttools==4.53.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - future==1.0.0
      - geopandas==1.0.1
      - get-annotations==0.1.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.65.5
      - gseapy==1.1.3
      - h11==0.14.0
      - h5py==3.11.0
      - harmonypy==0.0.10
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.5
      - humanfriendly==10.0
      - humanize==4.10.0
      - idna==3.7
      - igraph==0.11.6
      - imageio==2.34.2
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - inflect==7.3.1
      - inflection==0.5.1
      - ipykernel==6.29.5
      - ipython==8.18.1
      - isoduration==20.11.0
      - jax==0.4.30
      - jax-cuda12-pjrt==0.4.30
      - jax-cuda12-plugin==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - lightning==2.4.0
      - lightning-utilities==0.11.6
      - llvmlite==0.43.0
      - locket==1.0.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markovify==0.9.4
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - matplotlib-scalebar==0.8.1
      - matplotlib-venn==1.1.1
      - mdurl==0.1.2
      - mistune==3.0.2
      - mizani==0.9.3
      - ml-collections==0.1.1
      - ml-dtypes==0.4.0
      - more-itertools==10.3.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - mudata==0.2.4
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - multiprocess==0.70.16
      - multiscale-spatial-image==1.0.1
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numcodecs==0.12.1
      - numpy==1.26.4
      - numpyro==0.15.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.6.20
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - ome-zarr==0.9.0
      - omnipath==1.0.8
      - opencv-python==4.10.0.84
      - openslide-python==1.3.1
      - opt-einsum==3.3.0
      - optax==0.2.3
      - orbax-checkpoint==0.5.23
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - papermill==2.6.0
      - param==2.1.1
      - parso==0.8.4
      - partd==1.4.2
      - patsy==0.5.6
      - pexpect==4.9.0
      - pillow==10.4.0
      - pims==0.7
      - plac==1.4.3
      - platformdirs==4.2.2
      - plotnine==0.12.4
      - plotnine-prism==0.3.0
      - pooch==1.8.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==5.27.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pulp==2.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pyct==0.5.0
      - pydeprecate==0.3.1
      - pyfaidx==0.8.1.1
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyogrio==0.9.0
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - pyvcf3==1.0.3
      - pyyaml==6.0.1
      - pyzmq==26.1.0
      - referencing==0.35.1
      - regex==2024.7.24
      - reportseff==2.7.6
      - requests==2.32.3
      - reretry==0.11.8
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.19.1
      - rtoml==0.8.0
      - s3fs==2023.6.0
      - safetensors==0.4.3
      - scanpy==1.10.2
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scikit-misc==0.3.1
      - scipy==1.13.1
      - scvi-tools==1.1.5
      - seaborn==0.13.2
      - send2trash==1.8.3
      - session-info==1.0.0
      - shapely==2.0.5
      - slicerator==1.1.0
      - slurm-gpustat==0.0.15
      - smart-open==7.0.4
      - smmap==5.0.1
      - snakemake==7.32.4
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spatial-image==1.1.0
      - spatialdata==0.2.1
      - squidpy==1.6.0
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - stopit==1.1.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tblib==3.0.0
      - tenacity==9.0.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.64
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - throttler==1.2.2
      - tifffile==2024.7.24
      - timm==0.9.12
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - toolz==0.12.1
      - toposort==1.10
      - torch==2.4.0
      - torchaudio==2.4.0
      - torchmetrics==1.4.1
      - torchvision==0.19.0
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.43.3
      - triton==3.0.0
      - typeguard==4.3.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - umap-learn==0.5.6
      - unidecode==1.3.8
      - uri-template==1.3.0
      - validators==0.33.0
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - xarray==2024.7.0
      - xarray-dataclasses==1.8.0
      - xarray-datatree==0.0.14
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xgboost==2.1.1
      - xxhash==3.4.1
      - yarl==1.9.4
      - yte==1.5.4
      - zarr==2.18.2
      - zict==3.0.0
      - zipp==3.19.2
      - zstandard==0.23.0
